### ISSUE TITLE
Users using an ELB often end up with a misconfigured instance

### ISSUE THREAD

**Issue by rcmarron** [PostHog/posthog#10310]
## Is your feature request related to a problem?

I'm a bit out of my depth on this issue, but I've seen 3 customers hit an issue where they deploy PostHog on AWS behind a load balancer, and then all `next_urls` have `https://` flipped to `http://`, and as a result, all features that use paging are broken (e.g. loading large recordings, clicking next on the persons page etc.).

Setting the following in helm charts seems to fix it:

```
ingress-nginx:
    controller:
        config:
            use-forwarded-headers: "true"
web:
  secureCookies: false
  env:
    - name: TRUST_ALL_PROXIES
      value: "True"
```

## Describe the solution you'd like

Ideally, users wouldn't have to worry about this, and our default configurations handle this case properly.

## Describe alternatives you've considered

We could detect this is happening on the front-end, and show users a warning that points them to the documentation for how to fix it.

## Additional context

This issue eats up lots of support time because customers that report the bug report symptoms like 'this one recording won't load', and it's pretty difficult to debug back to 'this config is wrong'
