### ISSUE TITLE
Cannot deploy to Azure or run locally with Docker Compose

### ISSUE THREAD

**Issue by edmundmunday** [PostHog/posthog#1682]
## Bug description
When trying to deploy to Azure (https://posthog.com/docs/deployment/deploy-azure) cannot access the service.
There are a few issues, some we got past, others we did not.

1. The front-end app tries to run before the DB is ready, causing the web container to exit. This can be resolved by adding a "depends_on" to the redis section of docker-compose.yml and forcing it to wait for db before it runs. This is pretty flakey though as it's essentially just trying to buy the DB time. It does work though.

2. Once everything is actually running, cannot access the web app. When visiting the URL where the app is meant to be available you just get a 'connection refused'

Output from insomnia when used to ping the url"

` Preparing request to https://starrez-post-hog.westus.cloudapp.azure.com/
Current time is 2020-09-18T05:42:23.645Z
Using libcurl/7.69.1 OpenSSL/1.1.1g zlib/1.2.11 brotli/1.0.7 libidn2/2.1.1 libssh2/1.9.0 nghttp2/1.41.0
Using default HTTP version
Disable timeout
Enable automatic URL encoding
Enable SSL validation
Enable cookie sending with jar of 6 cookies
Hostname starrez-post-hog.westus.cloudapp.azure.com was found in DNS cache
  Trying 168.62.22.25:443...
Connection failed
connect to 168.62.22.25 port 443 failed: Connection refused
Failed to connect to starrez-post-hog.westus.cloudapp.azure.com port 443: Connection refused
Closing connection 2 `

## Expected behavior
1. shouldn't have to modify docker-compose.yml to get the web app to run without crashing.
2. once running, should be able to load the web-app.

## How to reproduce
1. Follow steps here: https://posthog.com/docs/deployment/deploy-azure
2. Modify docker-compose.yml and make redis depend_on db
3. Run docker-compose up
4. Attempt to open url
5. For bonus points, map a URL to the IP address in the Azure portal - still no dice.

## Environment

- PostHog cloud or self-managed?
self-managed
- PostHog version/commit
whatever the current master is...

**Comment by timgl** [comment]
@fuziontech would you mind taking a look when you wake up :)?

**Comment by morindo** [comment]
Any progress on this one? I'm having the same problem.

**Comment by edmundmunday** [comment]
@morindo - I've gotten it working now with a bit of help from @fuziontech and some additional work we had to do ourselves.

First we had to set the "DISABLE_SECURE_SSL_REDIRECT" environment variable to 'true' for the web container in the docker-compose file.
That should get it so you can connect to the Posthog application, but it will fail to setup because of there not being SSL on the connection.
We then had to add a reverse proxy to the base linux VM, setup https, and then point inbound traffic to the port exposed on the VM from Docker.
We used Caddy for the reverse proxy because it auto-manages SSL and is pretty easy to setup.
Caddy needs to be on the VM directly, not in docker. 
Finally, we set the "IS_BEHIND_PROXY" env variable in the Web container in the Docker-compose file to 'true'.

**Comment by trembylene** [comment]
The code for the Caddyfile and docker-compose file is below. YOUR_ADDRESS_HERE will need to be populated, valid address examples are listed here: https://caddyserver.com/docs/caddyfile/concepts#addresses

Caddyfile
```
YOUR_ADDRESS_HERE

reverse_proxy 0.0.0.0:8000
```

docker-compose.yml
```
version: '3'

services:
  db:
    image: postgres:alpine
    container_name: posthog_db
    environment:
      POSTGRES_USER: posthog
      POSTGRES_DB: posthog
      POSTGRES_PASSWORD: posthog
  redis:
    image: 'redis:alpine'
    container_name: posthog_redis
    depends_on:
      - db
  web:
    image: posthog/posthog:latest
    container_name: posthog_web
    ports:
      - '8000:8000'
    environment:
      IS_DOCKER: 'true'
      DATABASE_URL: 'postgres://posthog:posthog@db:5432/posthog'
      REDIS_URL: 'redis://redis:6379/'
      SECRET_KEY: ''
      SECURE_COOKIES: 'true'
      SITE_URL: YOUR_ADDRESS_HERE
      IS_BEHIND_PROXY: 'true'
      DISABLE_SECURE_SSL_REDIRECT: 'true'
    depends_on:
      - db
      - redis
    links:
      - db:db
      - redis:redis
```
