### ISSUE TITLE
Notebook (and maybe generally?) comments

### ISSUE THREAD

**Issue by benjackwhite** [PostHog/posthog#19167]
## Is your feature request related to a problem?

A feature request that has already come up internally is comments on Notebooks a la Google docs etc. 

This is one of those "iceberg" features that is simple on the face of it but has endless potential for scope and complexity creep so I wanted to outline what we could do to determine if it is worth the effort.

## Describe the solution you'd like

1. **Comment on Notebooks** It would be great if I can add a comment to any line of the document, including a "widget" that would somehow be indicated in the UI, opening the right hand side panel to show the comments when clicked
2. **Mentions** - Possibly underpinning this is the idea of mentions so that you can @mention someone and have a way for that person to be aware of all places they've been mentioned
3. **Replies** The next feature that would immediately be requested is replies - this would mean that any "comment" can get a follow up reply to make a thread like system
4. **Notifications** - Comments are only really useful if I would be made aware of them - this would be either via an @mention in the comment, or if it is my Notebook
  * We already have the activity panel - a somewhat okay solution would be to have some representation there for me to see all the comments I would be interested in
  * TRICKY - longer term people would want notifications which of course gets more complicated...
5. **Comments anywhere** - why keep this constrained to Notebooks? Could I attach comments to a feature flag? To an Insight? Massive scope creep...

It _feels_ like it would make a lot of sense to keep comments separate from Notebooks themselves.

```yaml
comment:
  - user: User
     timestamp: Date
     message: String
     notebook: String # ID of the notebook or "resource" to make it generic
     notebookIdentifier: String # Could be a nodeId or a line number
     deleted: boolean
```
