### ISSUE TITLE
Mapping xpaths to our product

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/posthog#2]
# Clarification

Language note: "users" can be confusing for us, given we track our users' users. I will refer to "clients" meaning the people using OUR software, and "users" meaning the users of their software.

# Product need

We track events automatically.

We track **front end events** because tracking back end events would require adapting to either different programming languages and/or databases, and would require our clients' developers to map these events - a technical marketer or product person wouldn't be able to do it.

We have the concept of an "Action". This is 1 or more events that are particularly important to our clients. For example, creating a user profile, submitting a blog post, running a search.

Multiple events could be the same Action - a form may appear in several places on a website, but it would do the same thing in the browser.

A key competitive advantage is that we track every event by default, so the tracking never loses information. 

This means that users need to be able to create actions, and then attach events to them.

Events also need properties "signed up" could then contain one of "with Google | with work email | with GitHub".

# Mapping UX

The first thing a user needs to do is to create an Action.

Then they need to be able to "go" to their app or website to tag the Action.

An Action is comprised of Steps. Steps contain Events.

This means we can add more logic to the steps if needed in future (IF/OR etc)

![Screenshot 2020-01-25 at 19 02 45](https://user-images.githubusercontent.com/47497682/73130012-6c754580-3fa5-11ea-906b-d024cea00e4a.png)

**Comment by jamesefhawkins** [comment]
CSS attached:

```css
body{
	background-color: #F7F6F3;
	caret-color: rgb(55, 53, 47);
	color: 37352F;
}

/* Use this for the word "PostHog" next to the logo */

.posthog-title{
	font-weight:500;
	font-size:36px;
	color: #333;
}

/* Use this for the logo */


.logo{
	width: 36px;
	background-image: "https://posthog.com/wp-content/uploads/elementor/thumbs/Instagram-Post-1hedgehog-off-black-ok61e8eds76dma39iqao8cwbeihgdc2a9grtrwy6p4.png";
}
```
