### ISSUE TITLE
service "temporal" depends on undefined service elasticsearch: invalid compose project

### ISSUE THREAD

**Issue by WebKenth** [PostHog/posthog#21705]
## Bug description

*Please describe.*
Following the guide on https://posthog.com/docs/self-host
running `/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/posthog/posthog/HEAD/bin/deploy-hobby)"` causes immediate docker-compose validation failure :(

## How to reproduce

1. visit https://posthog.com/docs/self-host 
2. run `/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/posthog/posthog/HEAD/bin/deploy-hobby)"`
3. output: `service "temporal" depends on undefined service elasticsearch: invalid compose project`

## Additional context

```
Docker version 26.0.2, build 3c863ff
Docker Compose version v2.13.0
```

Not sure what the error is reffering to, this is the snippet it breaks on:

![image](https://github.com/PostHog/posthog/assets/13419123/1f15466b-5f6d-4075-82a9-f54261489cf4)

```yml
    # Temporal containers
    elasticsearch:
        environment:
            - cluster.routing.allocation.disk.threshold_enabled=true
            - cluster.routing.allocation.disk.watermark.low=512mb
            - cluster.routing.allocation.disk.watermark.high=256mb
            - cluster.routing.allocation.disk.watermark.flood_stage=128mb
            - discovery.type=single-node
            - ES_JAVA_OPTS=-Xms256m -Xmx256m
            - xpack.security.enabled=false
        image: elasticsearch:7.16.2
        expose:
            - 9200
        volumes:
            - /var/lib/elasticsearch/data
    temporal:
        restart: on-failure
        environment:
            - DB=postgresql
            - DB_PORT=5432
            - POSTGRES_USER=posthog
            - POSTGRES_PWD=posthog
            - POSTGRES_SEEDS=db
            - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development-sql.yaml
            - ENABLE_ES=true
            - ES_SEEDS=elasticsearch
            - ES_VERSION=v7
        image: temporalio/auto-setup:1.20.0
        ports:
            - 7233:7233
        labels:
            kompose.volume.type: configMap
        volumes:
            - ./docker/temporal/dynamicconfig:/etc/temporal/config/dynamicconfig
        depends_on:
            db:
                condition: service_healthy
            elasticsearch:
                condition: service_started
```

### Debug info

```shell
- [ ] PostHog Cloud, Debug information: [please copy/paste from https://us.posthog.com/settings/project-details#variables]
- [x] PostHog Hobby self-hosted with `docker compose`, version/commit: latest
- [ ] PostHog self-hosted with Kubernetes (deprecated, see [`Sunsetting Kubernetes support`](https://posthog.com/blog/sunsetting-helm-support-posthog)), version/commit: [please provide]
```
