### ISSUE TITLE
Replay "message size too large" error

### ISSUE THREAD

**Issue by pauldambra** [PostHog/posthog#23703]
### Bug Description

We see these for multiple reasons
We can't ingest them
When we can't ingest a recording snapshot the chance of an unplayable recording is high
We need to minimise these

Kafka checks the size of a message before it compresses it so we need to be under 10MB _un_ compressed to be ingestible

We're gathering samples of these messages so that we can identify improvements

| file size | lib version | reason | things to try | tried in |
|--|--|--|--|--|
|67MB|1.146.1|426k attribute adds | * split incrementals in the SDK| v1.148.0 |
|36MB|1.146.0|massive data image urls | * redact large image urls| |
|34MB|1.146.1|250k attribute adds | * split incrementals in the SDK| v1.148.0 |
|15MB|1.145.0|lots of inlined css| * compress the text * send inlined css a different way| |
|11MB|1.86.1|many small incremental snapshots|* split the snapshots in capture * get customer to upgrade| |

|problems seen|count|
|--|--|
|super large rrweb data structure|5|
|large data urls|8|
|lots of inlined CSS|3|
|lots of small snapshots|1|

### only works for updated clients

- [ ] redact large data urls in the SDK
- [x] split large arrays of rrweb data in the SDK
- [ ] split large incremental snapshots in the SDK

### works for all clients

- [x] increase acceptable message size in ingestion (20MB HTTP (gzip compressed), 64MB WarpStream (not gzip compressed)
- [ ] compress in capture so warpstream/kafka client is accepting or not based on compressed size
- [ ] compress (full) snapshots throughout the pipeline

**Comment by daibhin** [comment]
The new asset stuff from rrweb might help a lot with sending the inlined CSS in a different way https://github.com/rrweb-io/rrweb/pull/1475

**Comment by sudo-eugene** [comment]
Does this issue have anything to do with `maskAllInputs: true` or `maskTextSelector: "*"`? I've tried masking everything I possibly can but I'm still getting the error with unplayable recording

**Comment by pauldambra** [comment]
Hey @sudo-eugene,

Normally that's not the issue here. The best bet is to report the problem using the in-app support flow since that lets us look into you recordings specifically to see what's best. Ideally if you can include example recordings that'd be awesome

**Comment by sudo-eugene** [comment]
@pauldambra this doesn't seem to be an issue in my PH cloud instance. It's only on my Self-Hosted instance that this happens. The issue report is, for reasons I understand, not available in the self-hosted version, hence my post here.

**Comment by pauldambra** [comment]
Ah, it's really hard to debug self-hosted since everyone's setup can vary so much. You can see in this issue the reasons we see this trigger. With large data urls and large amounts of CSS being the next largest un-addressed items.

**Comment by sudo-eugene** [comment]
Yes I suspect the CSS could be an issue our side. Could this potentially be due to inline CSS, or css files, or both?

Is there a way to disable/exclude CSS that I know won't be of value in our recordings?

**Comment by daibhin** [comment]
@sudo-eugene we mostly recommend to people with very large CSS bundles that they skip inlining it. This can be done when initializing the SDK:
```
posthog.init("API_KEY", {
	session_recording: {
        inlineStylesheet: false,
    }
})
```

Just so you know, this will mean that the files will be fetched during playback. If there are no longer available or have changed since capture your recordings might be unstyled

**Comment by lessless** [comment]
Just FYI: Sentry doesn't have any issues capturing same sessions

**Comment by sudo-eugene** [comment]
I've added all of these and still getting the error. I'll keep debugging to see if I can find anything, or get a base version working

```
        inlineStylesheet: false,
        maskAllInputs: true,
        maskTextSelector: "*"
```

**Comment by daibhin** [comment]
@sudo-eugene hmm sounds like it's not your CSS in that case. Would you mind opening a support ticket in-app or emailing me directly (david at posthog) so I can look into the specifics of your account

**Comment by flynet70** [comment]
Same problem
I added 
inlineStylesheet: false,
maskAllInputs: true,
maskTextSelector: "*"

to self hosted posthog

But still see "This session recording had recording data that was too large and could not be captured. This will mean playback is not 100% accurate."

**Comment by pauldambra** [comment]
Hey @flynet70 are you running the latest posthog including posthog-js v 1.166.x?

We're consistently improving these ingestion routes (or trying to :))

**Comment by flynet70** [comment]
Yes. I upgraded via
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/posthog/posthog/HEAD/bin/upgrade-hobby)"

posthog-js
https://posthog.mydomain.com/static/recorder.js?v=1.166.0 loads

Session replay works on main domain but 'too large' when I redirect to subdomain (billing system)
Checked in Chromium and Firefox.

But when i switch to cloud (api_host:'https://eu.i.posthog.com') - everything works well. Session replay works works in billing subdomain too. What is difference?

**Comment by flynet70** [comment]
I tried compare javascript loaded: cloud vs my host based

/static/array.js - identical
/static/recorder.js?v=1.166.0 - identical
/decide/?v=3&ip=1&_=1728447089625&ver=1.166.0&compression=base64 - has difference
left - cloud, right my host based

![Desktop-screenshot-10-09-2024_11_16_AM](https://github.com/user-attachments/assets/554d3424-e969-4a3b-ba5e-fecfdba05ca9)

**Comment by sudo-eugene** [comment]
I though perhaps is was the Kafka message size limit, so I set this, but it didn't work

```
            KAFKA_CFG_MESSAGE_MAX_BYTES: 67108864         # 64 MB
            KAFKA_CFG_REPLICA_FETCH_MAX_BYTES: 67108864   # 64 MB
            KAFKA_CFG_MAX_PARTITION_FETCH_BYTES: 67108864 # 64 MB
            KAFKA_CFG_MAX_REQUEST_SIZE: 67108864          # 64 MB
```

![Screenshot 2024-10-09 at 07 54 04](https://github.com/user-attachments/assets/5551a003-f223-4c30-b78a-650261dfb115)

**Comment by flynet70** [comment]
@pauldambra 
Do you have any idea?
May be we (with @sudo-eugene) need adjust some environment variables ?
Now i use default

**Comment by pauldambra** [comment]
I agree the next thing to try would be to increase message size over kafka. Assuming the kafka deployment is updated to accept larger messages you also need to set an environment variable to let the capture API know it's ok to ingest larger messages

`SESSION_RECORDING_KAFKA_MAX_REQUEST_SIZE_BYTES` in the web service

**Comment by sudo-eugene** [comment]
@flynet70 @pauldambra I added the `SESSION_RECORDING_KAFKA_MAX_REQUEST_SIZE_BYTES` in addition to the `KAFKA_CFG*` and it seems like it's working!

Thanks @pauldambra for the pointer.

Here's the docker-compose.yml:
```
services:
    ...
    kafka:
        extends:
            file: docker-compose.base.yml
            service: kafka
        depends_on:
            - zookeeper
        environment:
            KAFKA_LOG_RETENTION_MS: 3600000
            KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: 300000
            KAFKA_LOG_RETENTION_HOURS: 1
            KAFKA_CFG_MESSAGE_MAX_BYTES: 67108864         # Added 64MB to avoid "Message too large" error
            KAFKA_CFG_REPLICA_FETCH_MAX_BYTES: 67108864   # Added 64MB to avoid "Message too large" error
            KAFKA_CFG_MAX_PARTITION_FETCH_BYTES: 67108864 # Added 64MB to avoid "Message too large" error
            KAFKA_CFG_MAX_REQUEST_SIZE: 67108864          # Added 64MB to avoid "Message too large" error
        volumes:
            - kafka-data:/bitnami/kafka

    ...
    web:
        extends:
            file: docker-compose.base.yml
            service: web
        command: /compose/start
        volumes:
            - ./compose:/compose
        image: posthog/posthog:latest
        environment:
            ...
            SESSION_RECORDING_KAFKA_MAX_REQUEST_SIZE_BYTES: 67108864 # Added 64MB to avoid "Message too large" error
        depends_on:
            - db
            - redis
            - clickhouse
            - kafka
            - objectstorage
    ...
```
