### ISSUE TITLE
Events shown as stale even when events are sent

### ISSUE THREAD

**Issue by DogeAmazed** [PostHog/posthog#26107]
## Bug description
This happens to both PostHog event as well as custom events. They have the same behaviour.

Events are shown as stale in many places even though the events are shown on the Activity page

![billede](https://github.com/user-attachments/assets/bdd92bde-2b40-4826-a9d1-e4f1584cb16b)
Events are shown as "Last seen" a month ago.

![billede](https://github.com/user-attachments/assets/fbe10c5a-4322-47a6-b47e-60d0dd604fec)
Activity page show events are sent minutes ago but shown as stale when filtering. Also new events aren't even shown.

![billede](https://github.com/user-attachments/assets/9d5464ca-e887-49f4-bb9e-0f1a3d74d56d)

![billede](https://github.com/user-attachments/assets/1f690461-9e0d-4c62-9024-d58c6cf5ebe3)
Also web analytics is showing missing events

## How to reproduce
N/A

### Debug info

```shell
- [ ] PostHog Cloud, Debug information: [please copy/paste from https://us.posthog.com/settings/project-details#variables or https://eu.posthog.com/settings/project-details#variables]
- [ x ] PostHog Hobby self-hosted with `docker compose`, version/commit: d844b47438495358deddbac9cf13006e3fd72f0b
- [ ] PostHog self-hosted with Kubernetes (deprecated, see [`Sunsetting Kubernetes support`](https://posthog.com/blog/sunsetting-helm-support-posthog)), version/commit: [please provide]
```

**Comment by sweety3377** [comment]
same, please fix

**Comment by daltyboy11** [comment]
Also encountering this issue.

**Comment by gregegan** [comment]
Experiencing same issue.

**Comment by hafidoussous** [comment]
Also We have the same issue.

**Comment by torbjon** [comment]
```   
   property-defs-rs:
        image: ghcr.io/posthog/posthog/property-defs-rs:master
        build:
            context: posthog/rust/
            args:
                BIN: property-defs-rs
        restart: on-failure
        environment:
            DATABASE_URL: 'postgres://posthog:posthog@db:5432/posthog'
            KAFKA_HOSTS: 'kafka:9092'
            SKIP_WRITES: 'false'
            SKIP_READS: 'false'
            FILTER_MODE: 'opt-out'

    feature-flags:
        image: ghcr.io/posthog/posthog/feature-flags:master
        build:
            context: posthog/rust/
            args:
                BIN: feature-flags
        restart: on-failure
        volumes:
            - ./share:/share
        environment:
            WRITE_DATABASE_URL: 'postgres://posthog:posthog@db:5432/posthog'
            READ_DATABASE_URL: 'postgres://posthog:posthog@db:5432/posthog'
            MAXMIND_DB_PATH: '/share/GeoLite2-City.mmdb'
            REDIS_URL: 'redis://redis:6379/'
            ADDRESS: '0.0.0.0:3001'
            SKIP_WRITES: 'false'
            SKIP_READS: 'false'
```
should be added to docker compose and 

docker compose up --build property-defs-rs -d
docker compose up --build feature-flags -d
