### ISSUE TITLE
self-host bug list

### ISSUE THREAD

**Issue by straxico** [PostHog/posthog#28804]
hi i try use posthog self-host but i pause on start and spend many hour for find

1. latest instalable commit is 579408c765dc6a33cba571a558b553c1fff771c5  you most use `579408c765dc6a33cba571a558b553c1fff771c5` as docker tag for self-host
#28254 
#28448

2. events tab data not  show and cant use events for filter
#26107
 you most add this code to docker-compose
```
   property-defs-rs:
        image: ghcr.io/posthog/posthog/property-defs-rs:master
        build:
            context: posthog/rust/
            args:
                BIN: property-defs-rs
        restart: on-failure
        environment:
            DATABASE_URL: 'postgres://posthog:posthog@db:5432/posthog'
            KAFKA_HOSTS: 'kafka:9092'
            SKIP_WRITES: 'false'
            SKIP_READS: 'false'
            FILTER_MODE: 'opt-out'
```

3. live activity not work 
#26106
its fix on #7724fd847d45cc5c731c4e05cf47ef4790090435 but cant useable for me because error number 1

4. when i start record sessons all thing ok but after about 30 min . all things stop. all container up but panel not load and events not save . i give storage slow error but i cant find more details

**Comment by dix105** [comment]
@moufmouf  could you please tell me where shoudl i put NEW_CAPTURE_ENDPOINT this in my docker-compse.base.yml file

**Comment by moufmouf** [comment]
Sure!

Put it in the env vars of the "worker" service inside `docker-compse.base.yml`.

```
worker:
  environment:
       NEW_CAPTURE_ENDPOINT: '/e/'
```

I guess a better way would be to put that in the `docker-compse.yml` (it is the one we are supposed to overload) but I haven't tried that yet.

**Comment by dix105** [comment]
@moufmouf  thanks 
can you also look this issue [](https://github.com/PostHog/posthog/issues/28842)

**Comment by dix105** [comment]
@straxico can you please look into this issue also https://github.com/PostHog/posthog/issues/28842

**Comment by straxico** [comment]
> [@straxico](https://github.com/straxico) can you please look into this issue also [#28842](https://github.com/PostHog/posthog/issues/28842)

ok i see

**Comment by straxico** [comment]
> [@straxico](https://github.com/straxico) can you please look into this issue also [#28842](https://github.com/PostHog/posthog/issues/28842)

i have same error and after bind `user_defined_function.xml` and `user_scripts` its work fine. see top post i update it

![Image](https://github.com/user-attachments/assets/e8c0d994-3f9f-44a5-9fd0-686e1eb90b9b)

**Comment by dix105** [comment]
@straxico  i tried but got same error.

**Comment by solarvm** [comment]
@moufmouf @straxico 
for item 4 (CSRF issue). I've passed the var `NEW_CAPTURE_ENDPOINT` into worker/web containers, however still getting those 403s in logs:
```
2025-02-19T04:13:06.466025Z [warning  ] Forbidden (Origin checking failed - https://...EDITED... does not match any trusted origins.): /i/v0/e/ [django.security.csrf] container_hostname=5d5165896b98 host=ph....EDITED... pid=534 tid=129292627290432 token=phc_N6mtVTAKHr2cKJsGHUzv3IReUiS6vR3tgR5vD8B96eX x_forwarded_for=...EDITED...
2025-02-19T04:13:06.466096Z [warning  ] Forbidden (Origin checking failed - https://...EDITED... does not match any trusted origins.): /i/v0/e/ [django.security.csrf] container_hostname=5d5165896b98 host=ph....EDITED... pid=534 tid=129292627290432 token=phc_N6mtVTAKHr2cKJsGHUzv3IReUiS6vR3tgR5vD8B96eX x_forwarded_for=...EDITED...

```
has injection of that var resolved the issue completely for you?

**Comment by straxico** [comment]
> [@moufmouf](https://github.com/moufmouf) [@straxico](https://github.com/straxico) for item 4 (CSRF issue). I've passed the var `NEW_CAPTURE_ENDPOINT` into worker/web containers, however still getting those 403s in logs:
> 
> ```
> 2025-02-19T04:13:06.466025Z [warning  ] Forbidden (Origin checking failed - https://...EDITED... does not match any trusted origins.): /i/v0/e/ [django.security.csrf] container_hostname=5d5165896b98 host=ph....EDITED... pid=534 tid=129292627290432 token=EDITED x_forwarded_for=...EDITED...
> 2025-02-19T04:13:06.466096Z [warning  ] Forbidden (Origin checking failed - https://...EDITED... does not match any trusted origins.): /i/v0/e/ [django.security.csrf] container_hostname=5d5165896b98 host=ph....EDITED... pid=534 tid=129292627290432 token=EDITED x_forwarded_for=...EDITED...
> ```
> 
> has injection of that var resolved the issue completely for you?

i think your env not applyd. when set NEW_CAPTURE_ENDPOINT: '/e/' and run . not see any request point to /i/v0/e/ .
this way dont solve /i/v0/e/ csrf issues, its change endpoint from /i/v0/e/  to /e/

**Comment by dix105** [comment]
@straxico i have added 
 - ./posthog/posthog/idl:/idl
            - ./posthog/docker/clickhouse/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
            - ./posthog/docker/clickhouse/config.xml:/etc/clickhouse-server/config.xml
            - ./posthog/docker/clickhouse/users.xml:/etc/clickhouse-server/users.xml
            - ./docker/clickhouse/config.d/default.xml:/etc/clickhouse-server/config.d/default.xml
            - ./posthog/posthog/user_scripts:/var/lib/clickhouse/user_scripts
            - ./posthog/docker/clickhouse/user_defined_function.xml:/etc/clickhouse-server/user_defined_function.xml
            - clickhouse-data:/var/lib/clickhouse

but issue remain same

**Comment by solarvm** [comment]
> > [@moufmouf](https://github.com/moufmouf) [@straxico](https://github.com/straxico) for item 4 (CSRF issue). I've passed the var `NEW_CAPTURE_ENDPOINT` into worker/web containers, however still getting those 403s in logs:
> > ```
> > 2025-02-19T04:13:06.466025Z [warning  ] Forbidden (Origin checking failed - https://...EDITED... does not match any trusted origins.): /i/v0/e/ [django.security.csrf] container_hostname=5d5165896b98 host=ph....EDITED... pid=534 tid=129292627290432 token=EDITED x_forwarded_for=...EDITED...
> > 2025-02-19T04:13:06.466096Z [warning  ] Forbidden (Origin checking failed - https://...EDITED... does not match any trusted origins.): /i/v0/e/ [django.security.csrf] container_hostname=5d5165896b98 host=ph....EDITED... pid=534 tid=129292627290432 token=EDITED x_forwarded_for=...EDITED...
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > has injection of that var resolved the issue completely for you?
> 
> i think your env not applyd. when set NEW_CAPTURE_ENDPOINT: '/e/' and run . not see any request point to /i/v0/e/ . this way dont solve /i/v0/e/ csrf issues, its change endpoint from /i/v0/e/ to /e/

Still getting hits on that endpoint. Var is set at both composer files (base and override).
Just wonder maybe it should exist during the first db migrations? (i.e. do i need to reinstall the whole thing) or is it just a pure runtime var?

**Comment by moufmouf** [comment]
@solarvm 
To check if this is working, check in the network tabs of your dev-tools in your browser. You should not see any HTTP 403 anymore.

After applying the change, you can still occasionally see "Forbidden" errors because the web pages already loaded before you made the change will keep hitting the `/i/v0/e` endpoint.

**Comment by straxico** [comment]
> > > [@moufmouf](https://github.com/moufmouf) [@straxico](https://github.com/straxico) for item 4 (CSRF issue). I've passed the var `NEW_CAPTURE_ENDPOINT` into worker/web containers, however still getting those 403s in logs:
> > > ```
> > > 2025-02-19T04:13:06.466025Z [warning  ] Forbidden (Origin checking failed - https://...EDITED... does not match any trusted origins.): /i/v0/e/ [django.security.csrf] container_hostname=5d5165896b98 host=ph....EDITED... pid=534 tid=129292627290432 token=EDITED x_forwarded_for=...EDITED...
> > > 2025-02-19T04:13:06.466096Z [warning  ] Forbidden (Origin checking failed - https://...EDITED... does not match any trusted origins.): /i/v0/e/ [django.security.csrf] container_hostname=5d5165896b98 host=ph....EDITED... pid=534 tid=129292627290432 token=EDITED x_forwarded_for=...EDITED...
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > has injection of that var resolved the issue completely for you?
> > 
> > 
> > i think your env not applyd. when set NEW_CAPTURE_ENDPOINT: '/e/' and run . not see any request point to /i/v0/e/ . this way dont solve /i/v0/e/ csrf issues, its change endpoint from /i/v0/e/ to /e/
> 
> Still getting hits on that endpoint. Var is set at both composer files (base and override). Just wonder maybe it should exist during the first db migrations? (i.e. do i need to reinstall the whole thing) or is it just a pure runtime var?

dont need reinstall . when i change env and restart its apply.
its my code
```yaml
    web:
        extends:
            file: docker-compose.base.yml
            service: web
        command: /compose/start
        volumes:
            - ./compose:/compose
        image: posthog/posthog:579408c765dc6a33cba571a558b553c1fff771c5
        environment:
            SENTRY_DSN: 'https://aaaaaaaaa@sentry.aaaaaa.com/a'
            SITE_URL: https://posthog.jajiga.com
            SECRET_KEY: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
            OBJECT_STORAGE_ACCESS_KEY_ID: 'object_storage_root_user'
            OBJECT_STORAGE_SECRET_ACCESS_KEY: 'object_storage_root_password'
            OBJECT_STORAGE_ENDPOINT: http://objectstorage:19000
            NEW_CAPTURE_ENDPOINT: '/e/'
            OBJECT_STORAGE_ENABLED: true
            TRUST_ALL_PROXIES: true
            IS_BEHIND_PROXY: true
            DISABLE_PAID_FEATURE_SHOWCASING: true
            OPT_OUT_CAPTURE: true
            ENCRYPTION_SALT_KEYS: aaaaaaaaaaaaaaaaaaaaaaaaaa
        depends_on:
            - db
            - redis
            - clickhouse
            - kafka
            - objectstorage
```
