### ISSUE TITLE
Cannot access PostHog via curl without -L, even with DISABLE_SECURE_SSL_REDIRECT='true' and SECURE_COOKIES: 'false'

### ISSUE THREAD

**Issue by rilut** [PostHog/posthog#3029]
## Bug description

Cannot access PostHog via curl without -L, even with DISABLE_SECURE_SSL_REDIRECT='true' in the docker-compose.yml

## Expected behavior

curl localhost:8000

returns

```html
<!doctype html><html><head><title>PostHog</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="icon" href="/static/favicon-32x32.png" sizes="32x32"/>
<link rel="icon" href="/static/favicon-192x192.png" sizes="192x192"/>


<link href="/static/main.css" rel="stylesheet"></head><body>
<div id="bottom-notice" class="tricolor">
    <div>
        <span>Current branch: </span><b><code>unknown</code></b
        ><span>.</span>
    </div>
    <div>
        <span>PostHog running in </span><b><code>DEBUG</code></b> mode!
    </div>
    <div>
        <span>Current revision: </span><b><code>unknown</code></b
        ><span>.</span>
    </div>
    <button title="Close debug bar" onclick="document.getElementById('bottom-notice').remove()">
        <code>×</code>
    </button>
</div>

<script>if (typeof Object.entries === 'undefined' || typeof Array.prototype.flatMap === 'undefined') {
                var div = document.createElement('div')
                div.style.color = '#fef6f6'
                div.style.background = '#920c0c'
                div.style.padding = '5px 10px'
                div.innerHTML = 'You are using a really old browser. Please upgrade to fully enjoy PostHog!'
                document.body.prepend(div)
            }</script><div id="root"></div><script src="/static/main.js"></script></body></html>
```

## How to reproduce

1. Use docker-compose.yml with `DISABLE_SECURE_SSL_REDIRECT='true'` and `SECURE_COOKIES: 'false'`:
```yaml
services:
    db:
        container_name: posthog_db
        environment:
            POSTGRES_DB: posthog
            POSTGRES_PASSWORD: posthog
            POSTGRES_USER: posthog
        image: postgres:alpine
        volumes:
            - postgres-data:/var/lib/postgresql/data
    redis:
        container_name: posthog_redis
        image: redis:alpine
    web:
        container_name: posthog_web
        depends_on:
            - db
            - redis
        environment:
            DATABASE_URL: postgres://posthog:posthog@db:5432/posthog
            REDIS_URL: redis://redis:6379/
            SECRET_KEY: 7349fb5546001e83f6687a3f4198a0aa4485e6570af1008f31ad4605375b7318
            DISABLE_SECURE_SSL_REDIRECT: 'true'
            SECURE_COOKIES: 'false'
            IS_DOCKER: 'true'
            DEBUG: 'true'
        image: posthog/posthog:latest
        links:
            - db:db
            - redis:redis
        ports:
            - 8000:8000
              #- 80:8000
volumes:
    postgres-data:
version: '3'
```
2. `docker-compose up`
3. `curl localhost:8000` only gets empty response, instead of the expected behavior
4. open `http://ip_address:8000` in Chrome, nothing happens
5. `curl -L localhost:8000` got the expected returns
6. docker logs posthog_web (only redirects HEAD, no GET)
```100.122.17.69 - - [21/Jan/2021:09:34:57 +0000] "HEAD / HTTP/1.0" 302 0 "-" "-"
100.122.17.86 - - [21/Jan/2021:09:34:57 +0000] "HEAD / HTTP/1.0" 302 0 "-" "-"
100.122.17.127 - - [21/Jan/2021:09:34:57 +0000] "HEAD / HTTP/1.0" 302 0 "-" "-"
100.122.17.46 - - [21/Jan/2021:09:34:57 +0000] "HEAD / HTTP/1.0" 302 0 "-" "-"
100.122.17.104 - - [21/Jan/2021:09:34:57 +0000] "HEAD / HTTP/1.0" 302 0 "-" "-"
100.122.17.113 - - [21/Jan/2021:09:34:58 +0000] "HEAD / HTTP/1.0" 302 0 "-" "-"
100.122.17.96 - - [21/Jan/2021:09:34:58 +0000] "HEAD / HTTP/1.0" 302 0 "-" "-"
```

## Environment

- self-hosted PostHog, version/commit: 29c1ed9 (master)
