### ISSUE TITLE
k8s / reverese proxy / disable http

### ISSUE THREAD

**Issue by kilianc** [PostHog/posthog#355]
Hey!

I am trying to setup `posthog` with `k8s`.

After a little bit of debugging I realized there is a `301` to `https` - that won't work since we have everything behind a reverse proxy :/ 

![image](https://user-images.githubusercontent.com/385716/76697063-88b16c80-664f-11ea-87a9-793de5737ed3.png)

Is it possible to disable https?

**Comment by timgl** [comment]
Hey! Glad you got it working. Have a look at [Running behind a proxy](https://github.com/PostHog/posthog/wiki/Running-behind-a-proxy) to see if any of that helps?

**Comment by kilianc** [comment]
Here's the winner!

```yaml
kind: Deployment
apiVersion: apps/v1
metadata:
  name: posthog
spec:
  selector:
    matchLabels:
      app: posthog
  template:
    metadata:
      labels:
        app: posthog
    spec:
      containers:
      - name: posthog
        image: posthog/posthog:latest
        ports:
        - containerPort: 8000
        resources:
          limits:
            cpu: 95m
            memory: 285Mi
        env:
        - name: IS_DOCKER
          value: "true"
        - name: SECRET_KEY
          value: "---"
        - name: IS_BEHIND_PROXY
          value: "true"
        - name: DISABLE_SECURE_SSL_REDIRECT
          value: "true"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              key: database-url
              name: posthog
---
apiVersion: v1
kind: Service
metadata:
  name: posthog
  labels:
    app: posthog
spec:
  type: NodePort
  selector:
    app: posthog
  ports:
  - name: http
    port: 80
    targetPort: 8000
```
