### ISSUE TITLE
900Mb memory usage at idle

### ISSUE THREAD

**Issue by gempain** [PostHog/posthog#3888]
## In what situation are you experiencing subpar performance?

I've got two PostHog installs on two identical VPS (1 vCore, 2GB RAM, 20GB SSD). At idle, RAM usage is 5Mb for Redis, Postgres 600Mb and PostHog 800Mb. I've got other Postgres instances (for other apps) running with 6Mb RAM.

Both my VPSs were dead yesterday, after about 2-3 days of running PostHog on them.

## How to reproduce

1. Install PostHog on a 2GB RAM VPS using the following `docker-compose.yml`

```yaml
version: '3.7'

services:

  traefik:
    image: traefik:2.3
    restart: unless-stopped
    command:
      - '--accesslog=true'
      - '--providers.docker=true'
      - '--entrypoints.web.address=:80'
      - '--entrypoints.websecure.address=:443'
      - '--providers.docker.exposedbydefault=false'
      - '--entrypoints.web.http.redirections.entrypoint.to=websecure'
      - '--entrypoints.web.http.redirections.entrypoint.scheme=https'
      - '--certificatesresolvers.letsencrypt.acme.email=info@id6.io'
      - '--certificatesresolvers.letsencrypt.acme.storage=/acme.json'
      - '--certificatesresolvers.letsencrypt.acme.tlschallenge=true'
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /data/traefik/acme.json:/acme.json

  posthog_db:
    image: postgres:alpine
    environment:
      POSTGRES_DB: posthog
      POSTGRES_PASSWORD: posthog
      POSTGRES_USER: posthog
    volumes:
      - /data/posthog/postgres:/var/lib/postgresql/data

  posthog_redis:
    image: redis:alpine

  posthog_web:
    image: posthog/posthog:latest
    depends_on:
      - posthog_db
      - posthog_redis
    environment:
      DISABLE_SECURE_SSL_REDIRECT: "true"
      SECURE_COOKIES: "false"
      DATABASE_URL: postgres://posthog:posthog@posthog_db:5432/posthog
      REDIS_URL: redis://posthog_redis:6379/
    env_file:
      - .posthog.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.posthog.rule=Host(`posthog.company.com`)"
      - "traefik.http.services.posthog.loadbalancer.server.port=8000"
      - "traefik.http.routers.posthog.tls=true"
      - "traefik.http.routers.posthog.tls.certresolver=letsencrypt"
```

2. Wait 2-3 days
3. Your VPS is dead

## Environment

- [ ] PostHog Cloud
- [x] self-hosted PostHog, version/commit: result of `docker images`:
```
REPOSITORY                          TAG          IMAGE ID       CREATED        SIZE
posthog/posthog                     latest       934fb31bf12e   5 days ago     1.18GB
```
