### ISSUE TITLE
GeoIP does not work on self-hosted with ingress.nginx

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#6334]
## Bug description

I want to use geo-ip plugin on a self-hosted instance but it does not work when deploying with `ingress.nginx.enabled`. 

## Expected behavior

I would get geolocation data

## How to reproduce

1. Deploy on digitalocean, sign up
2. Go to project settings, drag bookmarklet to bar
3. Use bookmarklet (ex http site: http://scratchpads.org/explore/sites-list)
4. Go to events, see $ip starting with 10.x and no geoip headers

![image](https://user-images.githubusercontent.com/148820/136564364-062d32f8-515e-4449-83b0-820e4b0bfab4.png)

## Environment

- [ ] PostHog Cloud
- [x] self-hosted PostHog (ClickHouse-based), version/commit: 1.28.1
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

## Additional context

cc @yakkomajuri  @guidoiaquinti @tiina303 something for your team backlog

We have proxy-related environment variables `IS_BEHIND_PROXY`, `TRUSTED_PROXIES`, `TRUST_ALL_PROXIES` etc - these need to be checked.

**Comment by tristanratz** [comment]
We have the same issue – is this issue on the roadmap or is there anyway to contribute to a solution or a temporary workaround?

**Comment by guidoiaquinti** [comment]
I think I forgot to close this (see fix above ☝️). We've implemented the fix and we also added the related documentation to our website. Please re-open if I've missed anything. Thank you!

**Comment by MarcBrede** [comment]
@guidoiaquinti when is this expected to be part of a deployment that we can pull to our Posthog instance?

**Comment by guidoiaquinti** [comment]
Hey @MarcBrede, the fix has been merged in our helm chart repo on 15th Dec 2020. We also updated our documentations  with https://github.com/PostHog/posthog.com/pull/2554. Let me know if something is not clear, happy to help! 🙌

**Comment by MarcBrede** [comment]
> @guidoiaquinti when is this expected to be part of a deployment that we can pull to our Posthog instance?

According to the [docs](https://posthog.com/docs/self-host/deploy/digital-ocean), I added the proxy protocol to `values.yml`:
```
cloud: "do"
ingress:
  hostname: <hostname>
  nginx:
    enabled: true

ingress-nginx:
  controller:
    config:
      use-proxy-protocol: true
    service:
      annotations:
        service.beta.kubernetes.io/do-loadbalancer-hostname: <hostname>
        service.beta.kubernetes.io/do-loadbalancer-enable-proxy-protocol: "true"

cert-manager:
  enabled: true
```
and executed `helm upgrade -f values.yaml --install --timeout 20m --namespace posthog posthog posthog/posthog --atomic --wait --wait-for-jobs --debug`. It works now!
