### ISSUE TITLE
Running locally with docker

### ISSUE THREAD

**Issue by viperfx** [PostHog/posthog#636]
**Describe the bug**
Is there a way to run the project locally with docker by using the local file?

Desired functionality:
- runserver with reload
- webpack monitoring for front-end changes and building

Ive tried with the following config:

```
  web:
    restart: always
    build:
      context: .
      dockerfile: preview.Dockerfile
    command: ./bin/start
    volumes:
      - .:/code
    container_name: posthog_web
    ports:
      - target: 8000
        published: 8000
        protocol: tcp
        mode: host
```

However, I got an issue where it could not find the templates.

TemplateDoesNotExist at /setup_admin
layout.html

How does the team run posthog locally? Just by installing all the dependancies locally?
