### ISSUE TITLE
Any filter on the Paths crashes the app.

### ISSUE THREAD

**Issue by PaoloC68** [PostHog/posthog#823]
**Describe the bug**
Opening the paths page and selecting a  different period crashes  the whole site, no error reported, just a blank page

**To Reproduce**
1. Get Posthog 1.6.0
2. Host it on a owned server
3. Change the paths timeframe

**Expected behavior**

See the paths for the selected period

**Screenshots**

![Screen Shot 2020-05-21 at 14 58 25](https://user-images.githubusercontent.com/1483774/82591806-46883800-9b76-11ea-84a0-f051110700f5.png)

![Screen Shot 2020-05-21 at 15 18 39 1](https://user-images.githubusercontent.com/1483774/82591951-7d5e4e00-9b76-11ea-9099-34fdd1c65c13.png)

**Desktop (optional: please complete the following information):**
 - OS: Mac Os Mojave
 - Browser: Brave, Chrome, Safari
 - Version: Version 1.8.96 Chromium: 81.0.4044.138 (Official Build) (64-bit) ,Version 1.8.96 Chromium: 81.0.4044.138 (Official Build) (64-bit), Version 12.1.2 (14607.3.9)

**Additional context**
Posthog 1.6.0 on docker, this my docker-compose file:

```
version: '3'

networks:
  proxy:
    external: true
  internal:
    external: false

services:
  redis:
    image: "redis:5-alpine"
    container_name: posthog_redis
    restart: unless-stopped
    labels:
        - traefik.enable=false
    networks:
      - internal
  web:
    image: posthog/posthog:latest
    container_name: posthog_web
    ports:
      - "8000"
    restart: unless-stopped
    environment:
      IS_DOCKER: "true"
      IS_BEHIND_PROXY: "true"
      DISABLE_SECURE_SSL_REDIRECT: "true"
      DATABASE_URL: "postgres://postgres:postgres@postgres:5432/posthog"
      REDIS_URL: "redis://redis:6379/"
      SECRET_KEY: "<my secret>"
    depends_on:
      - redis
    networks:
      - internal
      - proxy
    labels:
      - traefik.frontend.rule=Host:posthog.mydomain.com
      - traefik.docker.network=proxy
      - traefik.port=8000
```
