### ISSUE TITLE
Migration guide for v1.30.0 hobby setups

### ISSUE THREAD

**Issue by radekmie** [PostHog/posthog#8500]
## Is your feature request related to a problem?

I'm using PostHog for nearly a year now and I'm **extremely** happy with it! As it's only for my personal blog, I had everything set up on a $5 DigitalOcean instance (along with a couple of other things). Everything is working as expected, and reasonably fast.

Today, I wanted to migrate to the latest version of PostHog. What I usually did, was to update the version in my Docker compose file, run `docker stack deploy --compose-file posthog.yml posthog`, and call it a day. (To be precise, I have a Traefik set up in place to take care of routing.)

<details>
<summary>Here's the content of <code>posthog.yml</code>.</summary>

```yml
version: '3'

services:
  posthog-postgres:
    image: postgres:13.4-alpine
    environment:
      POSTGRES_DB: REDACTED
      POSTGRES_PASSWORD: REDACTED
      POSTGRES_USER: REDACTED
    networks:
      - posthog
    volumes:
      - posthog-postgres-data:/var/lib/postgresql/data
  posthog-redis:
    image: redis:6.2.5-alpine
    networks:
      - posthog
  posthog:
    image: posthog/posthog:release-1.30.0
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.posthog-router.rule=Host(`posthog.REDACTED`)
        - traefik.http.routers.posthog-router.service=posthog-service
        - traefik.http.routers.posthog-router.tls
        - traefik.http.services.posthog-service.loadbalancer.server.port=8000
    environment:
      ASYNC_EVENT_PROPERTY_USAGE: 'true'
      DATABASE_URL: postgres://REDACTED:REDACTED@posthog-postgres:5432/REDACTED
      IS_BEHIND_PROXY: 'true'
      IS_DOCKER: 'true'
      REDIS_URL: redis://posthog-redis:6379/
      SECRET_KEY: REDACTED
      SITE_URL: https://posthog.REDACTED
    networks:
      - posthog
      - traefik-net

networks:
  posthog:
  traefik-net:
    external: true

volumes:
  posthog-postgres-data:
    external: true
```

</details>

As you may have already guessed, it's not the case this time. As I'm currently using version 1.30.0, I'd have to set up a ClickHouse instance now. And I was eager to do so, really! But there's literally zero information on how to do it other than using the Helm chart. And while I'm fine with switching to a larger instance to fit all of the required services, the migration itself is not clear to me.

I'm fine with some downtime, but it'd be great to make it as short as possible. I'm also fine to move some data by hand if needed!

## Describe the solution you'd like

I'd like to migrate my own instance of PostHog to the next (preferably latest) version. And as a side-effect, produce a migration guide for other people in a similar situation.

## Describe alternatives you've considered

I thought about migrating to PostHog Cloud, but it's a no-go for me due to privacy reasons. I'm not saying PostHog is doing anything bad - that's just my approach to these things.

## Additional context

I can provide you with literally every context you'll need. Just let me know!
