### ISSUE TITLE
loading animation/s

### ISSUE THREAD

**Issue by lottiecoxon** [PostHog/posthog#8903]
Initially @clarkus's suggestion of creating a more interesting loading sign for the app + ideas from @corywatilo = (hopefully) a cool outcome made by me...

For smaller loading spaces such as mobile/ small frames we will aim to have a logo themed loading animation. The shape and colours are recognisable even when scaled down and will make for an interesting geometric animation. 

For the larger loading spaces such as loading a query on desktop (which can sometimes take a few seconds) Cory had the idea to 'delight' users by giving them an animation of a hedgehog doing something technical - eg rapidly typing on a computer and keys flying off. To add to this every now and again (maybe every release) I could create another animation for this, meaning that every time a query loads the user is shown something different. Over time this could be a really good way of entertaining users. (as well as filling blank space and more importantly time in-between loads)

**Comment by corywatilo** [comment]
I'm going to remove this from the W&D sprint plan (since this is more app-related, but it would be great if we can still pick this up!)

**Comment by lottiecoxon** [comment]
## Loading Animations 

### Larger Loading State 

Running Tech Hedgehog 

https://user-images.githubusercontent.com/65415371/167866550-70293af0-192f-41f6-b36a-2994d0ebe8d8.mov

### Smaller Loading State

(first draft)

I took the shapes found within the logo and thought of a fun balancing composition. The colours are not decided on yet - it could adopt the real logo colours?

![Untitled_Artwork 6](https://user-images.githubusercontent.com/65415371/167865953-7383833f-a3f5-45b9-90f8-17e305d8b30c.gif)

**Comment by lottiecoxon** [comment]
![Screenshot 2022-05-11 at 15 55 02](https://user-images.githubusercontent.com/65415371/167880823-8ee07965-a49e-4ab9-b271-0ec2ccaf8986.png)


![Untitled_Artwork 8](https://user-images.githubusercontent.com/65415371/167880780-ab09ba31-d294-4a1d-9bf9-148ba4f6e601.gif)

**Comment by clarkus** [comment]
I really like the idea of the logo morphing into other objects. An idea to explore might be to reuse the colors and not the shapes to come up with a spinner. If things are built in SVG / vector, we could animate the shape changes. I like this idea a lot!

**Comment by lottiecoxon** [comment]
## So I ran with the idea of morphing the logo into something but...

It looks weird, and a little retro and gamey?

![Screenshot 2022-05-16 at 12 34 38](https://user-images.githubusercontent.com/65415371/168584312-e59bfba7-ea3a-4bf7-ac21-bbdbc52c9bed.png)

![Screenshot 2022-05-16 at 12 34 45](https://user-images.githubusercontent.com/65415371/168584324-677f8d1c-a4f5-438a-9a78-3a21fa268864.png)


## So! I went back to what works at the moment

Our current spinner feels a little too chunky and I thought to let it breath I would turn the spinner into a circle of dots. 
Over a few experiments I feel that a more oval shape feels more modern and fresh - also paired with a bunch of colours. 

![Screenshot 2022-05-16 at 12 35 47](https://user-images.githubusercontent.com/65415371/168584327-5240b6ee-ca97-439e-b500-ab1ec07e61ec.png)



https://user-images.githubusercontent.com/65415371/168583288-780b951c-b677-43a3-ac6e-8f555f1b15a1.mov

## Finally some hedgehog animations 
These are to be placed in the bigger loading spaces when things take a bit of time. Transitioning between 3 hedgehogs - one working out, one listening to music and the last looking confused at a laptop. My aim is to over time add to these and continue to spark joy! 

https://user-images.githubusercontent.com/65415371/168583800-fd13f5a2-6579-4d9c-ad4a-131ba16e1742.mov

**Comment by clarkus** [comment]
Love the exploration. I personally prefer the hedgehogs. Maybe we can reserve the smaller spinners for those cases where they're shown inline?

**Comment by lottiecoxon** [comment]
I was under the understanding that the spinners would be for the super small spaces that needed a loading icon?

**Comment by mariusandra** [comment]
These are really cool! 

There's still this technological and organisational question, for which I don't have the answer: how do we actually show them in the app? 

We currently have a very nice story on getting static images from Figma into the app, but not so for movies and animation. Ideally design would give engineering a file that's just "plug and play". But what format should that "file" be?

The hedgehog animation above is a 5MB movie, and the spinner is a 1.2MB file. That's not that much, but it's still a chunky asset on the web.

In contrast, the current spinner is about [2KB of code](https://github.com/PostHog/posthog/tree/58104d3a4306589f5b70cda283507868b512f712/frontend/src/lib/components/Spinner) (0.002MB) and looks like this:

```css
// css
.Spinner {
    animation: spin 1s infinite linear;
    display: block;
    width: 2rem;
    height: 2rem;
    flex-shrink: 0;
    color: var(--primary);
    transition: color 100ms ease;
    .Spinner__trace,
    .Spinner__overlay {
        display: block;
        fill: transparent;
        stroke: currentColor;
        stroke-width: 8px;
        transform-origin: center;
    }
    .Spinner__trace {
        opacity: 0.25;
    }
    .Spinner__overlay {
        animation: writhe 1.2s infinite ease both;
        stroke-linecap: round;
        stroke-dashoffset: -30;
        stroke-dasharray: 60;
    }
    &.Spinner--inverse,
    .LemonButton--primary & {
        color: #fff;
    }
    &.Spinner--sm {
        width: 1rem;
        height: 1rem;
    }
    &.Spinner--lg {
        width: 4rem;
        height: 4rem;
    }
}

@keyframes writhe {
    0% {
        stroke-dashoffset: -40;
        stroke-dasharray: 50;
    }
    50% {
        stroke-dashoffset: -30;
        stroke-dasharray: 70;
    }
    100% {
        stroke-dashoffset: -40;
        stroke-dasharray: 50;
    }
}
```

```ts
// html (inside some javascript)
export function Spinner({ size = 'md', type = 'primary', traceless = false, style }: SpinnerProps): JSX.Element {
    return (
        <svg
            className={clsx('Spinner', size && `Spinner--${size}`, type && `Spinner--${type}`)}
            style={style}
            viewBox="0 0 48 48"
            xmlns="http://www.w3.org/2000/svg"
        >
            {!traceless && <circle className="Spinner__trace" cx="24" cy="24" r="20" />}
            <circle className="Spinner__overlay" cx="24" cy="24" r="20" />
        </svg>
    )
}
```

Basically, we build a `svg` circle with a dotted line as its pattern, and then make it spin and pulsate via CSS animations.

This is the most compact way of animating things, and makes sense for a loading spinner that should load before anything else: you describe the visual effect you want to achieve through simple graphical primitives and some CSS animations/keyframes that manipulate their properties.

The code above won't work for Lottie's 8-color spinner, as we likely need 8 independently colored objects, not one round circle with a dot pattern on its border. Or perhaps we can use a gradient as the color of the circle's border. I'm not sure, but this will take from an hour to half a day of work for a frontend engineer to get right.

That's still half a day of work, that comes at the expense of something else. So I have a hard time seeing someone jump in and volunteer to implement this :(. 

This "css + svg + html" style will work for simple animations, but I think you will go crazy if you would implement the jumping hedgehogs as CSS + SVG animations. It's doable, but a huge undertaking (imagine 20x as much CSS that you need to make sense of). Thus it's not practical.

We could just embed the video, but perhaps there's some better way? 

I know there's [Lottie](https://github.com/LottieFiles/lottie-react) by Airbnb and its [react-lottie](https://github.com/LottieFiles/lottie-react) counterpart (and [LottieFiles](https://lottiefiles.com/) online service?) that we could use. 

That's about 250kb of code for the animation player, and compact files for the animations themselves. I think this could work well, but are there better ways or tools?

Ideally we should do as much upfront work as needed, so that design could start handing engineering files that we could just integrate and play directly, to avoid spending half a day of writing custom CSS animations...  🤔
